inherit_from: configs/Replica/My_experiment/replica_room1_base.yaml

data:
  exp_name: exp6
  output: output/Replica/room1_exp6

tracking:
  use_adaptive_lr: False
  lr_decay_factor: 0.95
  lr_decay_steps: 1250

mapping:
  use_adaptive_lr: True
  lr_decay_factor: 0.60
  lr_decay_steps: 500