inherit_from: configs/replica_experiments/base_config_replica.yaml
mapping:
  initial_lr_rot: 0.001
  initial_lr_trans: 0.001
tracking:
  initial_lr_rot: 0.001
  initial_lr_trans: 0.001
data:
  output: output/Replica/room1_exp18
  exp_name: room1_exp18
