inherit_from: configs/replica_experiments/base_config_replica.yaml
mapping:
  initial_lr_rot: 0.01
  initial_lr_trans: 0.01
  initial_lr_embed: 0.05
  initial_lr_decoder: 0.05
data:
  output: output/Replica/room1_exp13
  exp_name: room1_exp13
