inherit_from: configs/replica_experiments/base_config_replica.yaml
mapping:
  initial_lr_rot: 0.01
  initial_lr_trans: 0.01
tracking:
  initial_lr_rot: 0.01
  initial_lr_trans: 0.01
data:
  output: output/Replica/room1_exp17
  exp_name: room1_exp17
